Services
========

== Booking Reference Service
The booking reference service provides a unique reference each time it is called

*+GET:/booking_reference+*

e.g. GET to +http://127.0.0.1:9082/booking_reference+ might return *+123456+*

There are no error responses

== Train Data API

Retrieve information about a train service
------------------------------------------

WARNING: This structure has changed in this v2 release of the service!

*+GET:/data_for_train/<trainId>+*

e.g. a GET to +http://127.0.0.1:9081/data_for_train/local_1000+ would return a status of +200+ with
[source,javascript]
----
{ "seats" : {"1A": { "coach" : "A", "seat_number" : "1", "booking_reference" : ""},
             "2A": { "coach" : "A", "seat_number" : "2", "booking_reference" : ""},
             "3A": { "coach" : "A", "seat_number" : "3", "booking_reference" : ""},
             "4A": { "coach" : "A", "seat_number" : "4", "booking_reference" : ""},
             "1B": { "coach" : "B", "seat_number" : "1", "booking_reference" : ""},
             "2B": { "coach" : "B", "seat_number" : "2", "booking_reference" : ""},
             "3B": { "coach" : "B", "seat_number" : "3", "booking_reference" : ""},
             "4B": { "coach" : "B", "seat_number" : "4", "booking_reference" : ""},
             "5B": { "coach" : "B", "seat_number" : "5", "booking_reference" : ""},
             "6B": { "coach" : "B", "seat_number" : "6", "booking_reference" : ""},
             "7B": { "coach" : "B", "seat_number" : "7", "booking_reference" : ""},
             "8B": { "coach" : "B", "seat_number" : "8", "booking_reference" : ""},
             "1C": { "coach" : "C", "seat_number" : "1", "booking_reference" : ""},
             "2C": { "coach" : "C", "seat_number" : "2", "booking_reference" : ""},
             "3C": { "coach" : "C", "seat_number" : "3", "booking_reference" : ""},
             "4C": { "coach" : "C", "seat_number" : "4", "booking_reference" : ""}
           }
}

----

If a train with the supplied ID isn't found then the service returns a +404+ status and an error response
[source,javascript]
----
{
    "error": "Train with ID foo_bar was not found"
}
----

Reserving Seats
---------------
To reserve seats on a train, you'll need to make a POST request to this url:
+http://127.0.0.1:9081/reserve+
and attach form data for which seats to reserve.

There should be three fields:
+train_id+, +seats+, +booking_reference+
The +seats+ field should be a json encoded list of seat ids, for example:
+["1A", "2A"]+


The other two fields are ordinary strings. Note the server will prevent you
from booking a seat that is already reserved with another booking reference

The response is the new state of the train with ID +train_id+

Errors will be returned for invalid +train_id+, seats or when a seat is already booked (the whole reservation will fail in this case).

Clearing all reservations
-------------------------

*+GET:/reset/<trainId>+*

Remove all reservations on a particular train. Use it with care

The response is the new state of the train with ID +train_id+

An error will be returned for an invalid +train_id+
